[build]
  publish = "dist"
  command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/article/feed/"
  to = "/article/feed.xml"
  status = 301
